// Generated by CoffeeScript 1.9.3
(function() {
  var fs, hbs, templateData;

  fs = require('fs');

  hbs = require('handlebars');

  templateData = JSON.parse(fs.readFileSync(__dirname + "/src/template.json"));

  module.exports = {
    template: function(templateName, mode) {
      var template;
      template = hbs.compile(fs.readFileSync(__dirname + "/src/templates/" + templateName + ".hbs", 'utf8'));
      if (mode === 'dev') {
        return new hbs.SafeString(template(templateData));
      } else {
        return new hbs.SafeString("{{" + templateData.teamName + "/" + templateName + "}}");
      }
    }
  };

}).call(this);
