// Generated by CoffeeScript 1.9.3
(function() {
  var Helpers, fs, hbs, templateData;

  fs = require('fs');

  hbs = new Object();

  templateData = new Object();

  Helpers = (function() {
    function Helpers(handlebars, tplateData) {
      hbs = handlebars;
      templateData = tplateData;
      return {
        template: this.template,
        capitals: this.capitals,
        link: this.link
      };
    }

    Helpers.prototype.capitals = function(str) {
      return str.toUpperCase();
    };

    Helpers.prototype.link = function(linkName, mode) {
      if (linkName === 'index') {
        return "index.html";
      }
      if (mode === 'live') {
        return linkName;
      } else {
        return linkName + ".html";
      }
    };

    Helpers.prototype.template = function(templateName, mode) {
      var template;
      template = hbs.compile(fs.readFileSync(__dirname + "/src/templates/" + templateName + ".hbs", 'utf8'));
      if (mode === 'live') {
        return new hbs.SafeString("{{" + templateData.teamName + "/" + templateName + "}}");
      } else {
        return new hbs.SafeString(template(templateData));
      }
    };

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);
